apiVersion: v1
kind: Pod
metadata:
  name: pod-template
spec:
  containers:
    - name: devpod
      resources:
        requests:
          cpu: 2
      volumeMounts:
        - mountPath: /workspaces/.home
          name: devpod
          subPath: devpod/home
